### ISSUE TITLE
Update charts to be helm3 compliant + follow best practices

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-charts#144]
We have a bunch of older charts which were generated around helm2 templates. For helm3, there are some updates and improvements. The minimal set of which are not major changes, but if we are bumping the chart for helm3 (chart major version rev), we may as well implement other changes as well to bring all charts up-to-date with our internal best practices, such as including Service Monitors, etc.

This issue can be treated more like an epic/meta tracking issue. The list below encapsulates all the charts - each should be updated. For brand new ones, there is probably nothing to do other than verify the chart is up to date. For older ones, this could be adding in a lot of new templates, though the existing templating shouldn't change all that much since the deployment configuration for each app isn't changing -- just some of the templating around it.

**Note**: It's not clear to me what we do at this time with deprecated charts. I'm not sure we have really defined that part of a chart's lifecycle yet.

---

- [x] emulator
- [x] ~etamay~
- [x] juniper-jti
- [x] modbus
- [x] openconfig
- [x] prophetess
- [x] snmp-ups
- [x] snmp
- [x] synse-loadgen
- [x] synse-server

**Comment by edaniszewski** [comment]
question - do we still use etamay, or should the chart be deprecated?

**Comment by KylerBurke** [comment]
deprecated
