### ISSUE TITLE
update icon for charts

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-charts#2]
do we want to update the icon for the charts to something more synse-related? currently all the charts use the 'chamber' icon: http://www.vapor.io/wp-content/uploads/2016/01/Vapor_Chamber_Logo.png

**Comment by marcoceppi** [comment]
We absolutely do. I'll add that to my first pass after I find some good iconography

**Comment by marcoceppi** [comment]
What do you think about these:

# synse-server

![synse-server-chart](https://user-images.githubusercontent.com/70613/47679594-f6fca880-db9a-11e8-92d4-dce260e7cb26.jpg)

# snmp

![synse-snmp](https://user-images.githubusercontent.com/70613/47679603-ff54e380-db9a-11e8-9c35-7bac4c47e42d.jpg)

# modbus

![synse-modbus](https://user-images.githubusercontent.com/70613/47679612-067bf180-db9b-11e8-81e7-e80994dbf5dc.jpg)

# emulator

![synse-emulator](https://user-images.githubusercontent.com/70613/47679621-0c71d280-db9b-11e8-9ec4-9b3dc99116b2.jpg)

We have a few color options that keep up inline with branding. I also considered making the emulator icon a bit more 8bit as a reference to game emulation. I'm a big fan of this green though (`#A5CD39`)

**Comment by edaniszewski** [comment]
ohhh fancy! those look nice to me, i'm also a fan of the green

**Comment by marcoceppi** [comment]
These will work fine for placeholders, I'll add them into the current Migration branch

**Comment by edaniszewski** [comment]
@marcoceppi -- I think this should be good to close
