### ISSUE TITLE
update label used to identify synse plugins

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-charts#89]
Currently the label `synse-component: plugin` is used to identify synse plugins. This is used by synse-server, for example, to find/connect to plugins at  runtime.

Given that best practices are to namespace labels (e.g. `app.kubernetes.io/name`, `vapor.io/monitor` -- see also: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels), would it make sense to update this plugin label to something like:

```
vapor.io/synse: plugin
```

**Comment by lazypower** [comment]
Yeah! I'm all for this.

**Comment by edaniszewski** [comment]
closing -- this has been implemented in the latest updates for charts. we can also set any other labels we may want to use explicitly at config-time under the `service.labels` config option.
